[package]
name = "openreel-app"
build = "build.rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crossbeam-channel.workspace = true
eframe.workspace = true
openreel-agent = { path = "../openreel-agent" }
openreel-core = { path = "../openreel-core" }
openreel-media = { path = "../openreel-media" }
rfd.workspace = true
serde_json.workspace = true

[lints]
workspace = true

