//! CC8 §9.1 fixture 11 and §7's core half: migration, serialization, and the
//! managed HDR state.
//!
//! §10 step 9 is "Migration and serialization: fixture 11", and fixture 11
//! reads: "**Migration.** An SDR project opens, round-trips, and exports
//! byte-identically; an HDR-source/SDR-delivery project loads and blocks with
//! the typed reason."
//!
//! The half that needs an encoder — "exports byte-identically" — is
//! `kinewright_media::cc8_fixtures`'s, beside §9.1 fixture 6's exported-byte
//! gate. This file carries the half that is pure document state: the stored
//! bytes, the migration rules, §7 item 2's typed block, §7 item 4's
//! save/reopen/journal/undo/redo, and §2.4's static HDR metadata.
//!
//! # The two checked-in projects are real pre-CC8 artifacts
//!
//! `tests/fixtures/pre_cc8_sdr_project.json` and
//! `tests/fixtures/pre_cc8_hdr_source_sdr_delivery_project.json` are byte-frozen
//! project files in the exact form the serializer writes. Their provenance was
//! established rather than assumed: both were loaded and re-serialized by the
//! **pre-CC8 build** (commit `bbf8969`, "feat: complete CC7 workflow
//! evaluation", the last commit before any CC8 code) and came back
//! byte-for-byte, so the bytes this file asserts are unchanged are bytes CC7
//! itself wrote and read. That is what makes §7 item 1's obligation —
//! "**Every existing project opens byte-unchanged and exports byte-identically**"
//! — testable at all: a fixture generated by the build under test could only
//! ever prove self-consistency.
//!
//! CC0's migration precedent is `tests/fixtures/pre_m13_project.json`, which
//! `contracts.rs` and `cc1_conformance.rs` already read for the same purpose;
//! those tests are untouched and still pass, which is the CC0→CC1 half of the
//! same claim.

use std::sync::Arc;

use kinewright_core::{
    AssetId, BatchError, CC8_HDR_DELIVERY_LANE, CC8_MANAGED_HDR_STATE_RECOVERY, ColorContext,
    ColorDescription, ColorPipelineState, ColorProvenance, ColorSourceProfile,
    ColorSourceProfileAssumption, ColorWhitePoint, Command, ContentLightLevel, Core,
    DeliveryEncodeDepth, DeliveryLane, DeliveryProfile, Document, Event,
    HDR_SOURCE_ON_SDR_DELIVERY, HdrStaticMetadata, JournalCommand, MasteringDisplayChromaticity,
    MasteringDisplayMetadata, OpError, Operation, QaSeverity, TimelineRevision,
    cc8_hdr_delivery_description, classify_source, classify_source_with_assumption,
    delivery_conformance,
};

/// The byte-frozen pre-CC8 SDR project.
const PRE_CC8_SDR_PROJECT: &str = include_str!("fixtures/pre_cc8_sdr_project.json");

/// The byte-frozen pre-CC8 project whose source is HLG Rec.2020 and whose
/// delivery description is CC1's SDR Rec.709 — §7 item 2's project, and
/// fixture 11's second sentence.
const PRE_CC8_HDR_SOURCE_SDR_DELIVERY_PROJECT: &str =
    include_str!("fixtures/pre_cc8_hdr_source_sdr_delivery_project.json");

/// The delivery-conformance sample CC6 §6.2 uses in the other CC8 fixtures.
const CONFORMANCE_SAMPLE: (u8, u8) = (50, 50);

fn conformance(document: &Document) -> kinewright_core::DeliveryConformanceReport {
    delivery_conformance(
        document,
        DeliveryProfile::SourceMaster,
        DeliveryEncodeDepth::Ten,
        CONFORMANCE_SAMPLE.0,
        CONFORMANCE_SAMPLE.1,
    )
    .expect("a colour mismatch is reported, never returned as an error")
}

fn issue_codes(report: &kinewright_core::DeliveryConformanceReport) -> Vec<String> {
    report
        .issues
        .iter()
        .map(|issue| issue.code.clone())
        .collect()
}

// ---------------------------------------------------------------------------
// §9.1 fixture 11, first sentence: an SDR project opens and round-trips.
// ---------------------------------------------------------------------------

/// **§9.1 fixture 11 / §7 item 1.** Every pre-CC8 project opens byte-unchanged.
///
/// §7 item 1: "**Every existing project opens byte-unchanged and exports
/// byte-identically.** This is the strongest migration obligation in CC8 and §9
/// gates it. An SDR project must not acquire an HDR field, a changed delivery
/// description, or a different exported byte stream."
///
/// All three prohibitions are asserted, and the first one is asserted on the
/// **bytes** rather than on a field list, because a field list can only refuse
/// the fields its author thought of:
///
/// 1. the re-serialized document is byte-identical to the stored file;
/// 2. no CC8 spelling appears anywhere in those bytes; and
/// 3. the loaded delivery description and pipeline state are the ones the file
///    stored, and the project is still CC1-managed-SDR-compatible.
#[test]
fn cc8_pre_cc8_projects_open_byte_unchanged_and_acquire_no_hdr_field() {
    for (label, raw) in [
        ("sdr", PRE_CC8_SDR_PROJECT),
        (
            "hdr_source_sdr_delivery",
            PRE_CC8_HDR_SOURCE_SDR_DELIVERY_PROJECT,
        ),
    ] {
        let document: Document = serde_json::from_str(raw).expect("a pre-CC8 project opens");
        document.validate().expect("and it validates");

        let saved = format!(
            "{}\n",
            serde_json::to_string_pretty(&document).expect("and it saves")
        );
        assert_eq!(
            saved, raw,
            "{label}: a pre-CC8 project must re-save byte-for-byte",
        );

        for spelling in [
            "hdr_static_metadata",
            "managed_hdr_v1",
            "mastering_display",
            "content_light_level",
        ] {
            assert!(
                !saved.contains(spelling),
                "{label}: a pre-CC8 project acquired the CC8 field `{spelling}`",
            );
        }

        // The stored state, unchanged, and CC1's own question still answered
        // the way CC1 answers it.
        assert_eq!(
            document.color_context.pipeline_state,
            ColorPipelineState::ManagedSdrV1,
            "{label}",
        );
        assert_eq!(
            document.color_context.delivery,
            ColorContext::sdr_rec709().delivery,
            "{label}: the delivery description must not have moved",
        );
        assert!(
            document.color_context.is_managed_sdr_compatible(),
            "{label}"
        );
        assert!(
            !document.color_context.is_managed_hdr_compatible(),
            "{label}"
        );
        assert_eq!(
            DeliveryLane::for_description(&document.color_context.delivery),
            DeliveryLane::SdrRec709,
            "{label}",
        );

        // §2.4: absent metadata is unknown and stays unknown.
        for asset in &document.media_pool {
            assert!(
                asset.color_description.hdr_static_metadata.is_unknown(),
                "{label}: asset {} acquired declared HDR metadata",
                asset.id,
            );
        }

        // The compact form round-trips too, and a second load of what this
        // build wrote is the same document — the reopen half of §7 item 4.
        let compact = serde_json::to_string(&document).expect("compact save");
        let reopened: Document = serde_json::from_str(&compact).expect("compact reopen");
        assert_eq!(reopened, document, "{label}");
        assert_eq!(
            serde_json::to_string(&reopened).expect("compact re-save"),
            compact,
            "{label}",
        );
    }
}

/// **§9.1 fixture 11, second sentence / §7 item 2.** An HDR-source project on
/// an SDR delivery target loads and blocks with the typed reason.
///
/// §7 item 2: "A project whose source is HDR but whose delivery is SDR
/// **loads**, reports the mismatch, and blocks managed export with the §5.3
/// typed reason naming the deferral. It is not auto-tone-mapped and its
/// delivery target is not silently rewritten (§0.2 Q6)."
///
/// Each clause is a separate assertion, including the two negative ones: after
/// the report is taken, the document's delivery description and its source
/// description are compared against the bytes it was loaded from.
#[test]
fn cc8_pre_cc8_hdr_source_on_sdr_delivery_loads_and_blocks_with_the_typed_reason() {
    let document: Document = serde_json::from_str(PRE_CC8_HDR_SOURCE_SDR_DELIVERY_PROJECT)
        .expect("§7 item 2: it **loads**");
    document.validate().expect("and it validates");

    // The source really is one of §2.1's HDR profiles, so the block below is
    // about an HDR source rather than about an unclassifiable one.
    let source = &document.media_pool[0].color_description;
    assert_eq!(classify_source(source), Ok(ColorSourceProfile::HlgRec2020));

    let report = conformance(&document);
    let blocking = report
        .issues
        .iter()
        .find(|issue| issue.code == HDR_SOURCE_ON_SDR_DELIVERY)
        .expect("§7 item 2's typed reason must be reported");
    assert_eq!(blocking.severity, QaSeverity::Error);
    assert_eq!(blocking.asset, Some(AssetId(1)));
    assert!(
        blocking.message.contains("§0.2 Q6"),
        "the reason must name the deferral: {}",
        blocking.message,
    );
    assert!(!report.export_ready(), "{:?}", issue_codes(&report));

    // The two things §7 item 2 forbids: no rewrite, no tone map. The document
    // is compared to the bytes it came from rather than to a constructed
    // expectation, so any silent repair anywhere in the load or the report
    // shows up here.
    let saved = format!(
        "{}\n",
        serde_json::to_string_pretty(&document).expect("it saves")
    );
    assert_eq!(saved, PRE_CC8_HDR_SOURCE_SDR_DELIVERY_PROJECT);
}

// ---------------------------------------------------------------------------
// §7's managed HDR state.
// ---------------------------------------------------------------------------

/// **§7.** `managed_hdr_v1` is written by CC8 and never by a load.
///
/// §7: "the first CC8 save writes `managed_hdr_v1`; an absent value stays
/// `managed_sdr_v1` or `legacy`." Both halves are asserted here, and the second
/// is asserted on the case that would be most tempting to migrate: a project
/// that already stores an HDR delivery description. CC6 deliberately lets a
/// document hold a delivery target the export refuses, so such a project can
/// exist without CC8; stamping it on load would hand it an HDR export
/// capability it never asked for, which is exactly §7 item 1's "an SDR project
/// must not acquire ... a different exported byte stream".
#[test]
fn cc8_managed_hdr_state_is_written_by_cc8_and_never_stamped_by_a_load() {
    // The state CC8 writes, and its wire spelling.
    let context = ColorContext::hdr_hlg_rec2020();
    assert_eq!(context.pipeline_state, ColorPipelineState::ManagedHdrV1);
    let encoded = serde_json::to_value(&context).expect("the context serialises");
    assert_eq!(encoded["pipeline_state"], "managed_hdr_v1");
    let decoded: ColorContext = serde_json::from_value(encoded).expect("and round-trips");
    assert_eq!(decoded, context);

    // §3.1: only the delivery description differs from CC1's context.
    let sdr = ColorContext::sdr_rec709();
    assert_eq!(context.working, sdr.working);
    assert_eq!(context.monitoring, sdr.monitoring);
    assert_eq!(context.delivery, cc8_hdr_delivery_description());
    assert!(context.is_managed_hdr_compatible());
    assert!(!context.is_managed_sdr_compatible());
    assert!(context.is_managed_compatible());

    // An absent `pipeline_state` on a context that already names §5.1's lane
    // stays `legacy` — never `managed_hdr_v1`, and never `managed_sdr_v1`.
    let absent = serde_json::json!({
        "working": sdr.working,
        "monitoring": sdr.monitoring,
        "delivery": cc8_hdr_delivery_description(),
    });
    let migrated: ColorContext = serde_json::from_value(absent).expect("it loads");
    assert_eq!(migrated.pipeline_state, ColorPipelineState::Legacy);
    assert!(!migrated.is_managed_compatible());

    // A stored `managed_sdr_v1` beside an HDR delivery description stays
    // exactly that, and is refused as a managed pipeline rather than being
    // read as the HDR one.
    let mismatched = ColorContext {
        pipeline_state: ColorPipelineState::ManagedSdrV1,
        delivery: cc8_hdr_delivery_description(),
        ..ColorContext::sdr_rec709()
    };
    assert!(!mismatched.is_managed_compatible());
    let document = Document {
        color_context: mismatched,
        ..Document::default()
    };
    let report = conformance(&document);
    assert!(
        issue_codes(&report).contains(&"unsupported_color_pipeline_state".to_owned()),
        "{:?}",
        issue_codes(&report),
    );
    let issue = report
        .issues
        .iter()
        .find(|issue| issue.code == "unsupported_color_pipeline_state")
        .expect("checked above");
    assert!(
        issue.message.contains("managed_hdr_v1"),
        "{}",
        issue.message
    );
    assert!(
        issue.message.contains(CC8_MANAGED_HDR_STATE_RECOVERY),
        "the lane-aware state reason must carry its recovery action: {}",
        issue.message,
    );
}

/// **§7.** The two half-formed colour contexts `SetColorContext` refuses.
///
/// The state and the lane must name each other, in both directions. This is the
/// same rule §7 item 3 applies to the delivery description's own fields, one
/// level up: a project must not be able to store a context whose state and
/// target contradict each other and only fail much later, at export.
#[test]
fn cc8_managed_state_and_delivery_lane_must_name_each_other() {
    let cases = [
        (
            "managed_hdr_v1",
            ColorContext {
                pipeline_state: ColorPipelineState::ManagedHdrV1,
                ..ColorContext::sdr_rec709()
            },
            DeliveryLane::SdrRec709.as_str(),
            DeliveryLane::HdrHlgRec2020.as_str(),
        ),
        (
            "managed_sdr_v1",
            ColorContext {
                pipeline_state: ColorPipelineState::ManagedSdrV1,
                delivery: cc8_hdr_delivery_description(),
                ..ColorContext::sdr_rec709()
            },
            DeliveryLane::HdrHlgRec2020.as_str(),
            DeliveryLane::SdrRec709.as_str(),
        ),
    ];
    for (state, color_context, observed_lane, required_lane) in cases {
        let mut document = Document::default();
        let error = kinewright_core::apply_batch(
            &mut document,
            &[Operation::SetColorContext {
                color_context: color_context.clone(),
            }],
        )
        .expect_err("a half-formed managed context must be refused");
        assert_eq!(
            error,
            BatchError::OperationFailed {
                op_number: 1,
                error: OpError::ManagedColorStateLaneMismatch {
                    state,
                    observed_lane,
                    required_lane,
                    recovery: CC8_MANAGED_HDR_STATE_RECOVERY,
                },
            },
        );
        assert_eq!(
            document.color_context,
            ColorContext::default(),
            "a refused operation must leave the document untouched",
        );
    }

    // The passing direction, both lanes: each state applies on its own lane.
    for context in [ColorContext::sdr_rec709(), ColorContext::hdr_hlg_rec2020()] {
        let mut document = Document::default();
        kinewright_core::apply_batch(
            &mut document,
            &[Operation::SetColorContext {
                color_context: context.clone(),
            }],
        )
        .expect("a matched state and lane must apply");
        assert_eq!(document.color_context, context);
    }

    // `legacy` and a future state are untouched by this rule on the SDR side:
    // CC6 lets a document hold a delivery target its export refuses, and CC1 §4
    // keeps `legacy` readable. Only CC8's own state gained a constraint.
    for state in [
        ColorPipelineState::Legacy,
        ColorPipelineState::Other("managed_sdr_v2".to_owned()),
    ] {
        let mut document = Document::default();
        kinewright_core::apply_batch(
            &mut document,
            &[Operation::SetColorContext {
                color_context: ColorContext {
                    pipeline_state: state.clone(),
                    ..ColorContext::sdr_rec709()
                },
            }],
        )
        .expect("CC8 adds no rule to the SDR states CC1 and CC6 already defined");
        assert_eq!(document.color_context.pipeline_state, state);
    }
}

/// **§7 item 4.** Save/reopen, journal replay, undo, and redo preserve the
/// managed state, the source HDR metadata, and the profile assumption.
///
/// §7 item 4, verbatim: "Save/reopen, journal replay, undo, and redo preserve
/// the source HDR metadata, the profile assumption, and the managed state,
/// byte-for-byte apart from documented JSON defaults."
///
/// Three of the four things it names are stored state and are compared as
/// stored bytes here. The **profile assumption** is not stored anywhere and
/// deliberately so — CC1 §2.1's D65 assumption is derived from the raw
/// description at every call site (`classify_source_with_assumption`,
/// `hdr_source_profile_for_description`, the renderer's own `d65_assumption`),
/// and §2.1 requires the raw metadata to stay `Unknown`: "No code may rewrite
/// it." So the obligation on it is discharged by the description round-tripping
/// unchanged, and that is what is asserted — the same assumption, applied to
/// the same raw white point, yields the same profile after every step.
#[test]
fn cc8_hdr_state_survives_save_reopen_journal_replay_undo_and_redo() {
    let mut asset = kinewright_core::MediaAsset {
        color_description: ColorDescription {
            white_point: ColorWhitePoint::Unknown,
            hdr_static_metadata: declared_static_metadata(),
            ..hlg_source_description()
        },
        ..sdr_asset()
    };
    asset.id = AssetId(1);

    // The starting document: an HDR source, CC1's SDR context.
    let start = Document {
        media_pool: vec![asset.clone()],
        ..Document::default()
    };
    let core = Core::spawn(start).expect("the core starts");
    let operation = Operation::SetColorContext {
        color_context: ColorContext::hdr_hlg_rec2020(),
    };

    let Event::DocumentChanged {
        doc,
        revision: TimelineRevision(1),
        last_op: Some(last_op),
        journal_command: Some(journal_command),
    } = core
        .request(Command::Do(operation.clone()))
        .expect("applied")
    else {
        panic!("expected the HDR context to apply");
    };
    assert_eq!(last_op, operation);
    assert_eq!(journal_command, JournalCommand::Do(operation.clone()));
    assert_hdr_project(&doc, "applied");

    // Save and reopen, on the serialized bytes.
    let saved = serde_json::to_string(doc.as_ref()).expect("it saves");
    let reopened: Document = serde_json::from_str(&saved).expect("it reopens");
    assert_eq!(&reopened, doc.as_ref());
    assert_eq!(
        serde_json::to_string(&reopened).expect("it re-saves"),
        saved,
        "§7 item 4: byte-for-byte apart from documented JSON defaults",
    );
    assert_hdr_project(&Arc::new(reopened), "reopened");

    // Journal replay: the recorded command, through its serialized form, into a
    // fresh core over the same starting document.
    let journal_json = serde_json::to_string(&journal_command).expect("the journal serialises");
    let replayed_command: JournalCommand =
        serde_json::from_str(&journal_json).expect("and deserialises");
    assert_eq!(replayed_command, journal_command);
    let replay_core = Core::spawn(Document {
        media_pool: vec![asset],
        ..Document::default()
    })
    .expect("the replay core starts");
    let Event::DocumentChanged { doc: replayed, .. } = replay_core
        .request(Command::from(replayed_command))
        .expect("the journalled command replays")
    else {
        panic!("expected the replayed command to change the document");
    };
    assert_eq!(
        serde_json::to_string(replayed.as_ref()).expect("the replayed document saves"),
        saved,
        "journal replay must reproduce the same document bytes",
    );

    // Undo, then redo.
    let Event::DocumentChanged { doc: undone, .. } =
        core.request(Command::Undo).expect("undo is accepted")
    else {
        panic!("expected undo to change the document");
    };
    assert_eq!(
        undone.color_context,
        ColorContext::default(),
        "undo must restore the pre-operation context exactly",
    );
    assert_source_preserved(&undone, "undone");

    let Event::DocumentChanged { doc: redone, .. } =
        core.request(Command::Redo).expect("redo is accepted")
    else {
        panic!("expected redo to change the document");
    };
    assert_eq!(
        serde_json::to_string(redone.as_ref()).expect("the redone document saves"),
        saved,
        "redo must reproduce the same document bytes",
    );
    assert_hdr_project(&redone, "redone");
}

/// The managed state, the delivery lane, and the source, on one document.
fn assert_hdr_project(document: &Arc<Document>, label: &str) {
    assert_eq!(
        document.color_context.pipeline_state,
        ColorPipelineState::ManagedHdrV1,
        "{label}",
    );
    assert!(
        document.color_context.is_managed_hdr_compatible(),
        "{label}"
    );
    assert_eq!(
        DeliveryLane::for_description(&document.color_context.delivery),
        DeliveryLane::HdrHlgRec2020,
        "{label}",
    );
    assert_source_preserved(document, label);
}

/// The source description, its declared §2.4 metadata, and the profile the
/// derived D65 assumption still reaches.
fn assert_source_preserved(document: &Document, label: &str) {
    let description = &document.media_pool[0].color_description;
    assert_eq!(
        description.white_point,
        ColorWhitePoint::Unknown,
        "{label}: §2.1 — the raw source metadata stays Unknown",
    );
    assert_eq!(
        description.hdr_static_metadata,
        declared_static_metadata(),
        "{label}: §2.4's declared metadata must survive",
    );
    assert_eq!(
        classify_source_with_assumption(description, Some(ColorSourceProfileAssumption::D65)),
        Ok(ColorSourceProfile::HlgRec2020),
        "{label}: the derived profile assumption must still reach the same profile",
    );
    assert_eq!(
        classify_source(description),
        Err(kinewright_core::ColorSourceError::UnknownWhitePoint),
        "{label}: and it is still an assumption, not a rewritten field",
    );
}

// ---------------------------------------------------------------------------
// §2.4's static HDR metadata.
// ---------------------------------------------------------------------------

/// **§2.4.** Declared static HDR metadata serialises with its provenance,
/// round-trips exactly, and is absent from a description that has none.
///
/// §2.4: "Mastering-display primaries and MaxCLL/MaxFALL are read on probe
/// where the container carries them, **stored on the source description with
/// provenance**, and reported. They are never invented: absent metadata is
/// `Unknown` and stays `Unknown`."
///
/// The values are asserted in ST 2086's own integer units, which is how they
/// are stored: a declared value is the integer the bitstream carried, so
/// nothing here rounds and nothing is reconstructed from a float.
#[test]
fn cc8_declared_static_hdr_metadata_round_trips_with_its_provenance() {
    let description = ColorDescription {
        hdr_static_metadata: declared_static_metadata(),
        ..hlg_source_description()
    };
    let encoded = serde_json::to_value(&description).expect("it serialises");
    let metadata = &encoded["hdr_static_metadata"];
    assert_eq!(metadata["mastering_display"]["red"]["x_increments"], 34_000);
    assert_eq!(metadata["mastering_display"]["red"]["y_increments"], 16_000);
    assert_eq!(
        metadata["mastering_display"]["green"]["x_increments"],
        13_250
    );
    assert_eq!(metadata["mastering_display"]["blue"]["y_increments"], 3_000);
    assert_eq!(
        metadata["mastering_display"]["white_point"]["x_increments"],
        15_635
    );
    assert_eq!(
        metadata["mastering_display"]["min_luminance_ten_thousandths_nits"],
        1
    );
    assert_eq!(
        metadata["mastering_display"]["max_luminance_ten_thousandths_nits"],
        10_000_000
    );
    assert_eq!(
        metadata["mastering_display"]["provenance"],
        "container_metadata"
    );
    assert_eq!(metadata["content_light_level"]["max_cll_nits"], 1_000);
    assert_eq!(metadata["content_light_level"]["max_fall_nits"], 400);
    assert_eq!(
        metadata["content_light_level"]["provenance"],
        "stream_metadata"
    );

    let decoded: ColorDescription = serde_json::from_value(encoded).expect("it round-trips");
    assert_eq!(decoded, description);

    // A description with no declaration writes no field at all, which is what
    // keeps §7 item 1's byte-unchanged obligation true for every pre-CC8
    // project.
    let unknown = ColorDescription::unknown();
    assert!(unknown.hdr_static_metadata.is_unknown());
    let encoded = serde_json::to_string(&unknown).expect("it serialises");
    assert!(!encoded.contains("hdr_static_metadata"), "{encoded}");
    let decoded: ColorDescription = serde_json::from_str(&encoded).expect("it round-trips");
    assert_eq!(decoded, unknown);

    // §2.4 forbids inventing a value, so a partially written block is a typed
    // deserialization failure rather than a source that declared zero nits.
    let truncated = serde_json::json!({
        "primaries": "bt2020",
        "hdr_static_metadata": { "content_light_level": { "max_cll_nits": 1000 } },
    });
    serde_json::from_value::<ColorDescription>(truncated)
        .expect_err("a half-written light-level block must not default to zero");

    // Declared metadata is source-side evidence and changes no target-side
    // answer: it is not part of §5.3's check order, and it does not make a
    // description stop being §5.1's lane.
    let lane_with_metadata = ColorDescription {
        hdr_static_metadata: declared_static_metadata(),
        ..cc8_hdr_delivery_description()
    };
    assert!(
        kinewright_core::delivery_color_mismatches(&lane_with_metadata).is_empty(),
        "§5.3's vocabulary and check order are unchanged by §2.4",
    );
}

/// **§5.1.** The core's HDR delivery description is the authority table's row.
///
/// The constructor writes typed enum values; the table stores wire spellings.
/// Asserting them equal here is what lets `ColorContext::hdr_hlg_rec2020` be
/// written from the enums without becoming a second transcription of §5.1.
#[test]
fn cc8_hdr_delivery_description_is_section_5_1s_lane_table() {
    let description = cc8_hdr_delivery_description();
    let lane = CC8_HDR_DELIVERY_LANE;
    assert_eq!(description.primaries.wire(), lane.primaries);
    assert_eq!(description.transfer.wire(), lane.transfer);
    assert_eq!(description.matrix.wire(), lane.matrix);
    assert_eq!(description.range.wire(), lane.range);
    assert_eq!(description.white_point.wire(), lane.white_point);
    assert_eq!(
        description.bit_depth.integer_bits(),
        Some(lane.bit_depth_bits)
    );
    assert_eq!(description.provenance, ColorProvenance::ApplicationDefault);
    assert!(description.hdr_static_metadata.is_unknown());
    assert_eq!(
        DeliveryLane::for_description(&description),
        DeliveryLane::HdrHlgRec2020
    );
    assert!(kinewright_core::delivery_color_mismatches(&description).is_empty());
}

// ---------------------------------------------------------------------------
// Shared source values.
// ---------------------------------------------------------------------------

/// The §2.4 declaration used throughout: BT.2020 mastering-display primaries
/// with a 1 000-nit peak, and CTA-861.3 light levels — the values §0.3(a)'s
/// measured transcript writes and re-probes, in ST 2086's own units.
fn declared_static_metadata() -> HdrStaticMetadata {
    HdrStaticMetadata {
        mastering_display: Some(MasteringDisplayMetadata {
            red: MasteringDisplayChromaticity {
                x_increments: 34_000,
                y_increments: 16_000,
            },
            green: MasteringDisplayChromaticity {
                x_increments: 13_250,
                y_increments: 34_500,
            },
            blue: MasteringDisplayChromaticity {
                x_increments: 7_500,
                y_increments: 3_000,
            },
            white_point: MasteringDisplayChromaticity {
                x_increments: 15_635,
                y_increments: 16_450,
            },
            min_luminance_ten_thousandths_nits: 1,
            max_luminance_ten_thousandths_nits: 10_000_000,
            provenance: ColorProvenance::ContainerMetadata,
        }),
        content_light_level: Some(ContentLightLevel {
            max_cll_nits: 1_000,
            max_fall_nits: 400,
            provenance: ColorProvenance::StreamMetadata,
        }),
    }
}

/// §2.1's `hlg_rec2020` tuple, as a probed source description.
fn hlg_source_description() -> ColorDescription {
    let document: Document = serde_json::from_str(PRE_CC8_HDR_SOURCE_SDR_DELIVERY_PROJECT)
        .expect("the frozen HDR-source project opens");
    document.media_pool[0].color_description.clone()
}

/// The frozen SDR project's asset, reused so this file constructs no second
/// media shape.
fn sdr_asset() -> kinewright_core::MediaAsset {
    let document: Document =
        serde_json::from_str(PRE_CC8_SDR_PROJECT).expect("the frozen SDR project opens");
    document.media_pool[0].clone()
}
