[package]
name = "openreel-media"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cpal.workspace = true
crossbeam-channel.workspace = true
ffmpeg-next.workspace = true
openreel-core = { path = "../openreel-core" }
pollster.workspace = true
rtrb.workspace = true
wgpu.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true

